### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by rchastain** [fredvs/swp#2]
Hello Fred!

Interesting project. Compiled successfully on Linux Mageia. But when I try to play the default URL, it seems to work but there is no sound. Would you have an idea?

**Comment by fredvs** [comment]
Hello Roland!
Did you try with the release I just uploaded now?
Just to see if it is a problem with your compilation.

**Comment by fredvs** [comment]
Note that if you click on the right button of the url-edit, there are other radios, maybe try a other.
![simplewebplayer_history](https://github.com/user-attachments/assets/8f3c70e3-f1a3-437e-ab5b-ec5704cd954f)

**Comment by fredvs** [comment]
Note that the release was compiled with fpc 3.2.4.
With fpc 3.2.2 I was not able to access http**s** url.
By the way, there is a asset of fpc-ootb 3.2.4. added in last release.
https://github.com/fredvs/freepascal-ootb/releases/

**Comment by rchastain** [comment]
With another radio, same result. With your binary, same result.

If you want, I can ask the question on the french Mageia forum, so that they help to identify the problem?

**Comment by rchastain** [comment]
> Note that the release was compiled with fpc 3.2.4. With fpc 3.2.2 I was not able to access http**s** url.

It doesn't seem to be the issue, because I see the equalizer moving.

**Comment by fredvs** [comment]
Strange, I have tested on a other machine and it works ok.
Also, on both machines (one Debian 10 and other last Xubuntu) multi-arch, version 32 and 64 bit work.
Can you see the wave form and did you try to recorder and play the result?
Maybe Mageia forum can help.

**Comment by fredvs** [comment]
Hello Roland!
Did you get some infos from Mageia forum?
I am downloading Maegia release 9 (4.2 gigas) but it will take some time, I dont have a fast connection ... (ETA 8 h 43 m !).
Then I will install it on a VMWare vitual machine and test it.
[EDIT] Ooops, only 1.34 giga downloaded and ETA 12 h 24 m !, so I will pause it for today.

**Comment by rchastain** [comment]
Not yet asked the question.

I confirm that the recorder works.

P. S. [Discussion](https://www.mageialinux-online.org/forum/topic-31624-essai-de-simple-webstream-player.php) created.

**Comment by fredvs** [comment]
Hello Roland.

Many thanks for the discussion.
I have take a look at the answer, it talks about **libsndfile.so** but that library is not used for the project SWP.
The good news is that **libmpg123.so** works for you (recording is ok).

Could you try loading the **libportaudio2.so** of your system?

For this, in  webstreamer.pas, line 400 (of last commit):
change this:
` if uos_LoadLib(PChar(pa), nil, PChar(mp), nil, nil, nil) = -1 then`
with that (keeping lib mp):
` if uos_LoadLib('system', nil, PChar(mp), nil, nil, nil) = -1 then`

Thanks.

(The download of Mageia continue, ETA: 3h 45m)

**Comment by fredvs** [comment]
Hello Roland!

OK, Mageia 9 + update installed.

First try with StrumPract release to see if sound works.
OK, it works.

Then with swp release.
The sound works but not fluently, it is like the sound driver take time to sent the datas to the sound card, a few samples are played, then silence, then other few samples.
I have seen that Mageia has his own custom sound-server Pulse Audio, maybe something to configure there.

I will check it one of those free-nights.

![magea_swp](https://github.com/user-attachments/assets/b639b423-8173-4132-9139-0bcbfaf1be2b)

**Comment by rchastain** [comment]
> Could you try loading the **libportaudio2.so** of your system?
> 

It doesn't solve the issue.

```
[roland@localhost src (main)]$ LC_ALL=C ./simplewebplayer 
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (/lib64/libsndfile.so.1: undefined symbol: mpg123_info2)
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (/lib64/libsndfile.so.1: undefined symbol: mpg123_info2)
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (/lib64/libsndfile.so.1: undefined symbol: mpg123_info2)
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (/lib64/libsndfile.so.1: undefined symbol: mpg123_info2)
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
[roland@localhost src (main)]$ 
```

**Comment by fredvs** [comment]
The debug text you showed is normal.
The sound is enabled and working but does not produce sound (or random).
I am busy to install fpc + dependencies via the Maegia install app but there are error when i click on the button, with lot of "Wait" or "Close".
Is it possible to install fpc and the binutils dependencies via terminal?
I absolutely new with Maegia.

**Comment by fredvs** [comment]
Hello Roland.

OK, I get it.
Mageia dont like the setting I did for Latency, better to let it choose.
Also the buffer of sample was a little to little.
I will commit it asap.
[EDIT] Done with commit: 51f58bb895efb76644584e28fc39de45e68c5e54
            Also updated the binaries in the release.

If you want to try, just change this
` webinindex := uos_AddFromURL(webindex, PChar(ansistring(historyfn.Value)), -1, aformat, 1024 * 2, 0, False);`
with this
` webinindex := uos_AddFromURL(webindex, PChar(ansistring(historyfn.Value)), -1, aformat, 1024 * 8, 0, False);`

and this
`  weboutindex := uos_AddIntoDevOut(webindex, -1, 1.5, uos_InputGetSampleRate(webindex, webinindex),  uos_InputGetChannels(webindex, webinindex), aformat, 1024 * 2, -1);`
with this
`  weboutindex := uos_AddIntoDevOut(webindex, -1, -1, uos_InputGetSampleRate(webindex, webinindex),  uos_InputGetChannels(webindex, webinindex), aformat, 1024 * 8, -1);`

and last this
`    uos_AddIntoFile(webindex, PChar(arec), -1, -1, aformat, 1024 * 2, 0);`
with this
`    uos_AddIntoFile(webindex, PChar(arec), -1, -1, aformat, 1024 * 8, 0);`

Here, on Mageia 9 VMWare machine, the sound is fluent and applying DSP also work nice.

Many thanks to show this Roland.

Fre;D

**Comment by fredvs** [comment]
Video of swp on Mageia (after the fix of course!)

https://github.com/fredvs/test/releases/download/fpc323/mageia_swp.mp4

**Comment by fredvs** [comment]
The last for tonight.
There was a other problem with Mageia, when trying to play a other url after the first url (that played good) it was no sound again.
It is fixed in last commit 24c3a27df7a46b80b3b585465171ea09d46a2d70
Also binary in release updated.

Video of swp on Mageia (after the fix of course!)
https://github.com/fredvs/test/releases/download/fpc323/mageia_swp.mp4

I hope all is good now.

Fre;D

**Comment by rchastain** [comment]
Hello Fred. Sorry, but here it still doesn't work. I have just tried again with your latest code:

```
[roland@localhost src (main)]$ ./simplewebplayer 
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (/lib64/libsndfile.so.1: undefined symbol: mpg123_info2)
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (/lib64/libsndfile.so.1: undefined symbol: mpg123_info2)
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (/lib64/libsndfile.so.1: undefined symbol: mpg123_info2)
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (/lib64/libsndfile.so.1: undefined symbol: mpg123_info2)
Cannot connect to server socket err = Aucun fichier ou dossier de ce type
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

Note: Illegal Audio-MPEG-Header 0xe5ccc15d at offset 615.
Note: Trying to resync...
Note: Skipped 93 bytes in input.

Warning: Big change from first (MPEG version, layer, rate). Frankenstein stream?
[roland@localhost src (main)]$ 
```

**Comment by fredvs** [comment]
Hello Roland.

;-(

What version of Mageia are you using?
I use Mageia 9 and here all works like charm.
What sound server do you use?
I use the default Pulse Audio, I did try with PipeWire but no sound at all for my machine.
I suppose that you did try also with the binary-release.
I dont have idea why it works for me and not for you.

![mageia1](https://github.com/user-attachments/assets/73ecea46-ee6a-4967-949c-ee58830a5afa)

![mageia3](https://github.com/user-attachments/assets/09897e55-d04b-4466-af20-09ed70caeb76)

![mageia2](https://github.com/user-attachments/assets/72ba4b2a-b201-4c29-b692-4f9e5f399ebb)

**Comment by fredvs** [comment]
>  I did try with PipeWire but no sound at all for my machine.

Wrong!
I did try with PipeWire and it works too.
So, I am lost, I dont understand why it does not work for you.

![mageia5](https://github.com/user-attachments/assets/aa4a244e-55b7-4cad-8155-1665c2f9a151)

**Comment by fredvs** [comment]
Re-...-re hello Roland.
I confirm that using audio-server "PipeWire with PipeWire Media Session" does not give sound.
But all other audio-server work here.


This does not give sound:
![mageia7](https://github.com/user-attachments/assets/03f1627a-407f-400b-a1a3-1147e208b5e5)

**Comment by rchastain** [comment]
It's Mageia 9. The sound server selected is PulseAudio with Glitch-Free.

I will try with other servers, to see if it changes something.

Yes, I also tested your latest binaries.

**Comment by fredvs** [comment]
>It's Mageia 9. The sound server selected is PulseAudio with Glitch-Free.

Hum, very strange, here it works with PulseAudio.

**Comment by fredvs** [comment]
Re-hello Roland.
In last commit added Menu Config Audio Devices.
You will have a list of all the devices of your system.
Maybe changing the default could help.
[EDITED] Updated the binary in release too.

![simpleplayer_device2](https://github.com/user-attachments/assets/31e8294f-edd6-4342-aff9-89d3b8eb3b67)

**Comment by rchastain** [comment]
Thank you Fred.

When I choose HDA Intel PCH, it works! Excepted that I cannot switch to my bluetooth speaker, but it's already something.

![swp](https://github.com/user-attachments/assets/e4378642-c127-4cf7-b4bd-e858823b666e)

There must be some cleaning to do in the menu management code, because at some moment the _Config_ menu item becomes disabled.

By the way, where can we find a list of web radios?

**Comment by fredvs** [comment]
Hello Roland!
Nice that something finally works.
The config menu is disabled when playing or recording to not disturb the selection done before it.
For list of radios, I dont know, I did a search by Google for "webradio site" but sure there must be sites specialized for that.

I will try with a bluetooth machine to see what goes there.
Many thanks for your attention.

Fre;D

**Comment by fredvs** [comment]
Hello Roland.
I have try with BlueTooth loudspeakers and here it is ok.
The BlueTooth connection is done by XUbuntu and sound is working.
That connection is shared with the virtual Maegia VMWare, so it is not a fair try for Mageia, but here the sound works too in Mageia virtual.

Also in last commit was added a "Update Audio Devices" menu to refresh the list of devices if a new device was added ( it works only if the player has stopped )

![swp_bluetooth_xubuntu](https://github.com/user-attachments/assets/2de81ad5-1bde-4ab1-b7e1-3d8825d81782)

![swp_bluetooth_mageia](https://github.com/user-attachments/assets/ed0e47fe-7554-455f-ade1-6c44d86ceea3)

**Comment by rchastain** [comment]
OK Fred. I will try the latest version.

By the way, the icon used for the Stop button is not usual. Is there a reason?

**Comment by fredvs** [comment]
Huh, no...
And it not a icon, only the caption of the button: Play = '>', Pause = '||', Resume = '>>'.
And for Stop, I was thinking of '>|'.
Do you have a other idea, using character, maybe 'S' should be better?
[Edit] Or maybe this one '[]' ?

**Comment by rchastain** [comment]
Why not 'S'. Or a [square](https://fr.wikipedia.org/wiki/Table_des_caract%C3%A8res_Unicode/U25A0).

**Comment by fredvs** [comment]
Yes the square is the best but I did not see it in the ascii table.
In the link you give there is no square character to copy, so I have to do some research.
And the 'S' is nice too.

**Comment by fredvs** [comment]
Ooops, no it is possible to copy the char, I think I will vote for this: '□'.

![simpleplayer_stop](https://github.com/user-attachments/assets/01b88480-be9c-4989-9ae4-11af8f1504b1)


Thanks Roland!

[EDIT] There is a new release with all the fixes and changes.

**Comment by fredvs** [comment]
Hello Roland.
In last release, you may choose what device to use from the audio server you selected in Mageia Control Center / Hardware / Sound Configuration  (PulseAudio, PulseAudio with Glitch, PipeWire, or PipeWire Media).
uos cannot select a sound-server, only the devices recognized by each sound-server, selecting a sound-server can only be done with root-access and reboot.

But, it seems to me that the list of devices you show me in your post https://github.com/fredvs/swp/issues/2#issuecomment-2308007302 is very short.
It is like your Sound Server dont recognize the virtual devices, like PulseAudio.
If you take a look at the screenshot I posted there https://github.com/fredvs/swp/issues/2#issuecomment-2307624049 , you will see the "hard root" devices, like "Ensonic AudioPCI", but also all the virtual devices, like vdownmix, sysdefault, etc...

Also strange that if you select device 3 that is the same as default device it works but if you select Default device it does not work.

But that's all part of the mystery of computers and part of its charm. (Perhaps).

**Comment by fredvs** [comment]
Re-hello Roland.
I updated in last commit + release the devices list with better check for name of default device.
Also all the device "In" (input) are disabled, no need to try this.
Maybe it solves something in your part.

![simpleplayer_9](https://github.com/user-attachments/assets/76bc71c9-144f-4a26-b40f-263e90a58f11)
